server:
  port: 8083
dubbo:
  application:
    name: web_item
  registry:
    address: zookeeper://192.168.227.138:2181
  consumer:
    check: false
    timeout: 60000
spring:
  rabbitmq:
    host: 192.168.227.138
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin