spring:
  datasource:
    url: jdbc:mysql:///shop1901
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #配置数据库连接池为阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000
  rabbitmq:
    host: 192.168.227.138
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
  redis:
    host: 192.168.227.138
dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.227.138:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
#mybatisplus的映射文件扫描
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/mapper/*.xml