spring:
  data:
    solr:
      host: http://192.168.227.138:8080/solr
  rabbitmq:
    host: 192.168.227.138
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
dubbo:
  application:
    name: service_search
  registry:
    address: zookeeper://192.168.227.138:2181
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 60000