spring:
  datasource:
    url: jdbc:mysql:///shop1901
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_server
  registry:
    address: zookeeper://192.168.227.138:2181
  protocol:
    name: dubbo
    port: -1